use rnn_training::model::Rnn;
use rnn_training::{Result, data};
use rand::SeedableRng;
use rand::rngs::StdRng;
use rand::seq::SliceRandom;
use std::collections::HashMap;

const DATA_DIR: &str = "/home/tarstars/database/shad/generate_text/ru";
const SEED: u64 = 42;
/// Names containing a character seen fewer times than this are dropped.
const MIN_CHAR_COUNT: usize = 10;
const VAL_FRACTION: f64 = 0.1;
const HIDDEN_SIZE: usize = 200;
/// Names per SGD step. The gradient is averaged over the batch, so a bigger
/// batch wants a bigger learning rate than batch size 1 does.
const BATCH_SIZE: usize = 32;
const LEARNING_RATE: f32 = 0.05;
/// The norm of all gradients together is clipped to this before the update.
const GRAD_CLIP: f32 = 50.0;
const EPOCHS: usize = 5;
/// Print the running train loss every this many names.
const LOG_EVERY: usize = 10_000;
/// How many generated names to print next to each loss.
const N_SAMPLES: usize = 3;
/// Generated names are cut off at this length.
const MAX_SAMPLE_LEN: usize = 40;

/// `N_SAMPLES` names generated by the current model, comma-separated.
fn samples(rnn: &Rnn, alphabet: &[char], char2ind: &HashMap<char, usize>, rng: &mut StdRng) -> String {
    let (start, end) = (char2ind[&data::START], char2ind[&data::END]);
    (0..N_SAMPLES)
        .map(|_| {
            rnn.sample(start, end, &[], MAX_SAMPLE_LEN, 1.0, rng)
                .iter()
                .map(|&i| alphabet[i])
                .collect::<String>()
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn main() -> Result<()> {
    let mut rng = StdRng::seed_from_u64(SEED);

    let names = data::load_names(DATA_DIR)?;
    let n_loaded = names.len();
    let rare = data::rare_chars(&names, MIN_CHAR_COUNT);
    let names = data::drop_names_with(names, &rare);
    let (alphabet, char2ind) = data::build_alphabet(&names);
    let (train, val) = data::split_train_val(names, VAL_FRACTION, &mut rng);

    println!(
        "names: {n_loaded} loaded, {} dropped for rare characters",
        n_loaded - train.len() - val.len()
    );
    println!("train: {} val: {}", train.len(), val.len());
    println!(
        "alphabet ({}): '{}'",
        alphabet.len(),
        alphabet.iter().collect::<String>()
    );

    let mut rnn = Rnn::new(alphabet.len(), HIDDEN_SIZE, &mut rng);
    println!("parameters: {}", rnn.n_params());
    println!("batch size: {BATCH_SIZE}, learning rate: {LEARNING_RATE}, clip: {GRAD_CLIP}");

    let mut train: Vec<Vec<usize>> = train.iter().map(|n| data::encode(n, &char2ind)).collect();
    let val: Vec<Vec<usize>> = val.iter().map(|n| data::encode(n, &char2ind)).collect();

    // Losses are reported per predicted character, in nats.
    // A model that guesses uniformly scores ln(alphabet size).
    println!("uniform guess loss: {:.3}", (alphabet.len() as f32).ln());

    for epoch in 1..=EPOCHS {
        train.shuffle(&mut rng);

        let (mut loss_sum, mut n_chars) = (0.0, 0);
        let mut names_seen = 0;
        for batch in train.chunks(BATCH_SIZE) {
            let (loss, grads) = rnn.train_batch(batch);
            rnn.sgd_update(LEARNING_RATE, GRAD_CLIP, grads.each_ref());
            loss_sum += loss;
            n_chars += batch.iter().map(|seq| seq.len() - 1).sum::<usize>();
            // Log once this batch has carried `names_seen` past a multiple of LOG_EVERY.
            let crossed = (names_seen + batch.len()) / LOG_EVERY > names_seen / LOG_EVERY;
            names_seen += batch.len();
            if crossed {
                println!(
                    "  epoch {epoch}, {names_seen:>6} names: train loss {:.3} | {}",
                    loss_sum / n_chars as f32,
                    samples(&rnn, &alphabet, &char2ind, &mut rng)
                );
                (loss_sum, n_chars) = (0.0, 0);
            }
        }

        let val_loss: f32 = val.iter().map(|seq| rnn.forward_sequence(seq).1).sum();
        let val_chars: usize = val.iter().map(|seq| seq.len() - 1).sum();
        println!(
            "epoch {epoch}: val loss {:.3} | {}",
            val_loss / val_chars as f32,
            samples(&rnn, &alphabet, &char2ind, &mut rng)
        );
    }

    Ok(())
}
